services:
  database:
    container_name: psmysql
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 12345:3306
  object-storage:
    container_name: minio
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
  socket:
    container_name: socket-server
    env_file:
      - .env
    build: socket-server/
    ports:
      - 8080:8080
